DATASET: joint
MODEL:
  BUILD_LOC: True
  LOC_SCORES_POS_AFFINE: True
  BBOX_REG_AS_FCN: True
  CTRL:
    LINEAR_MODULE_WEIGHTS: False
    USE_WORD_EMBED: True
  NMN:
    STACK:
      LENGTH: 8
      GUARD_STACK_PTR: True
    DESCRIBE_ONE:
      KEEP_STACK: True
    DESCRIBE_TWO:
      KEEP_STACK: True
TRAIN:
  USE_GT_LAYOUT: True
  MAX_ITER: 200000
  BBOX_IND_LOSS_WEIGHT: 0.5
  BBOX_OFFSET_LOSS_WEIGHT: 0.5
  DROPOUT_KEEP_PROB: 1.0