MODEL:
  BUILD_LOC: True
  LOC_SCORES_POS_AFFINE: True
  BBOX_REG_AS_FCN: True
  CTRL:
    LINEAR_MODULE_WEIGHTS: True
    USE_WORD_EMBED: True
  NMN:
    STACK:
      LENGTH: 8
      GUARD_STACK_PTR: True
    DESCRIBE_ONE:
      KEEP_STACK: True
    DESCRIBE_TWO:
      KEEP_STACK: True
TRAIN:
  USE_GT_LAYOUT: False
  MAX_ITER: 200000

  USE_SHARPEN_LOSS: True
  SHARPEN_LOSS_WEIGHT: 1e-1
  SHARPEN_SCHEDULE_BEGIN: 150000
  SHARPEN_SCHEDULE_END: 160000
